apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  selector:
    app: recommendation
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080